### ISSUE TITLE
Row styling missing

### ISSUE THREAD

**Issue by kotecekk** [TheInsomniac/Nginx-Fancyindex-Theme#7]
There is no row styling.

![1](https://cloud.githubusercontent.com/assets/9058216/4872953/378a1afa-61fa-11e4-8e8a-9ebcf00c8b2f.jpg)

fancyindex v0.3.4
nginx v1.7.7

**Comment by kotecekk** [comment]
Had to add:

``` css
tr:nth-child(even) {
    background-color: #F7F7F7;
}
```
